# This is a basic workflow to help you get started with Actions
name: RMSKIN Packager

on:
  push:
  pull_request:
  release:
    types:
      - published
      # - edited

jobs:
  Build_n_Release:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout this Repo
        uses: actions/checkout@v3

      # Runs a rmskin packager action
      - name: Run Build action
        id: builder
        uses: 2bndy5/rmskin-action@v1.1.8

      # upload the output from the `builder` step as workflow artifact
      - name: Archive rmskin file as artifact
        uses: actions/upload-artifact@v3
        if: github.event_name != 'release'
        with:
          name: ${{ steps.builder.outputs.arc_name }}
          path: ${{ github.workspace }}/${{ steps.builder.outputs.arc_name }}

      # Upload the asset
      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.builder.outputs.arc_name }}
          asset_content_type: application/zip
