# This is a basic workflow to help you get started with Actions
name: RMSKIN Packager

on:
  push:
    branches: [main, master]
    tags:
      - "*"
  pull_request:
    branches: [main, master]

jobs:
  Build_n_Release:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout this Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Runs a rmskin packager action
      - name: Run Build action
        id: builder
        uses: 2bndy5/rmskin-action@cefb988ebf291b17d3d4dc442d3ac8cb162dde64 # v2.0.4

      # upload the output from the `builder` step as workflow artifact
      - name: Archive rmskin file as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ${{ steps.builder.outputs.arc-name }}
          path: ${{ steps.builder.outputs.arc-name }}
          if-no-files-found: error

      # Upload the asset
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        run: gh release upload "${TAG}" "${ASSET_PATH}"
        env:
          TAG: ${{ github.ref_name }}
          ASSET_PATH: ${{ steps.builder.outputs.arc-name }}
          GITHUB_TOKEN: ${{ github.token }}
